// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOHrF3RFJYAklEQ8H8TxRfY-ZXw9U2cHU',
    appId: '1:310429796131:web:56efc239a706d4b0ae2e96',
    messagingSenderId: '310429796131',
    projectId: 'stocktrackerapp-1b88d',
    authDomain: 'stocktrackerapp-1b88d.firebaseapp.com',
    storageBucket: 'stocktrackerapp-1b88d.firebasestorage.app',
    measurementId: 'G-1YZR59GPBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL6K5U2C263Ysb2X5g5pcwTN_vVmJCwr4',
    appId: '1:310429796131:android:d43f711b8a31d787ae2e96',
    messagingSenderId: '310429796131',
    projectId: 'stocktrackerapp-1b88d',
    storageBucket: 'stocktrackerapp-1b88d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8bZ_y_qhfGXCeXg8chHUyqhkUrvqG0Z0',
    appId: '1:310429796131:ios:861dad697422ccaaae2e96',
    messagingSenderId: '310429796131',
    projectId: 'stocktrackerapp-1b88d',
    storageBucket: 'stocktrackerapp-1b88d.firebasestorage.app',
    iosBundleId: 'com.example.stocktrackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8bZ_y_qhfGXCeXg8chHUyqhkUrvqG0Z0',
    appId: '1:310429796131:ios:861dad697422ccaaae2e96',
    messagingSenderId: '310429796131',
    projectId: 'stocktrackerapp-1b88d',
    storageBucket: 'stocktrackerapp-1b88d.firebasestorage.app',
    iosBundleId: 'com.example.stocktrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOHrF3RFJYAklEQ8H8TxRfY-ZXw9U2cHU',
    appId: '1:310429796131:web:7e22bba0833cfa33ae2e96',
    messagingSenderId: '310429796131',
    projectId: 'stocktrackerapp-1b88d',
    authDomain: 'stocktrackerapp-1b88d.firebaseapp.com',
    storageBucket: 'stocktrackerapp-1b88d.firebasestorage.app',
    measurementId: 'G-0R4SV0X7X6',
  );
}
